### ISSUE TITLE
Need mod reload to stay on settings...

### ISSUE THREAD

**Issue by Himbraut** [Xpazeman/tld-weight-tweaks#9]
I played a while with this mod but since the last days, the settings canceled after loading screens. So often my char is overcrumbed when entering a house. I need to go to settings again, change a bit and save again to reload the settings fo this mod. I dont know if there is a issue with other mods I use but its the one and only I use for changing capacity.

**Comment by Xpazeman** [comment]
Probably a conflict or the product of some error. Settings are handled by ModSettings and not the mod itself
